test_configs:
  - name: "gemini-2.5-pro"
    input_path: "problem_set/IPhO/2025/test.jsonl"
    output_path: "test_results/IPhO/2025/single-llm/gemini-2.5-pro/results.jsonl"
    scheme: "single-llm"
    temperature: 0.0
    models:
      generator: "gemini/gemini-2.5-pro"
    single_llm_options:
      structured_output: true
    tools: []


global_settings:
  concurrent_limit: 10
  aux_dir_base: ".aux"
